#!/bin/bash

set -e -u -o pipefail
# set -x

info() {
    echo -e "\x1b[32m\xE2\x87\x92 $1\x1b[0m"
}

error() {
    echo -e "\x1b[97m\x1b[41m\x21\x1b[0m \x1b[31m$1\x1b[0m" 1>&2
    exit 1
}

warning() {
    echo -e "\x1b[97m\x1b[45m\x21\x1b[0m $1"
}

install_rust() {
    # https://github.com/rust-lang-nursery/rustup.rs
    # https://github.com/phildawes/racer

    info "Installing rust..."
    curl https://sh.rustup.rs -sSf | sh

    info "Installing rust nightly..."
    rustup toolchain install nightly

    info "Installing rust bash completion.."
    rustup completions bash > /etc/bash_completion.d/rustup.bash-completion

    info "Download rust source code and documentation..."
    rustup component add rust-src
    rustup component add rust-docs
    rustup update

    info "Installing racer..."
    cargo install racer

    info "Installing rustfmt..."
    cargo install rustfmt

    [[ -z $RUST_SRC_PATH ]] && warning "RUST_SRC_PATH does not seem to be defined"
}

create_src_dir() {
    info "Creating source directory..."
    sudo mkdir -vp /usr/local/src/rust/
}

create_symlinks() {
    info "Creating symlinks..."

    local plateform
    local os_type="$(uname -s)"

    case "$os_type" in
        Linux)
            plateform="stable-x86_64-unknown-linux-gnu"
            ;;
        Darwin)
            plateform="stable-x86_64-apple-darwin"
            ;;
        *)
          error "Unrecognized OS type: $os_type"
    esac

    sudo ln -svf "$HOME/.cargo/bin/racer" /usr/local/bin/racer
    sudo ln -svf "$HOME/.rustup/toolchains/${plateform}/lib/rustlib/src/rust/src" /usr/local/src/rust/src
}

main() {
  command -v rustc >/dev/null 2>&1 || install_rust
  create_src_dir
  create_symlinks
}

main
